name = "FluxConservative"
uuid = "a0a2aac6-15cc-11ea-0b06-3779f982b5e6"
authors = ["Igor Kroener <igor.kroener@awi.de>"]
version = "0.1.0"

[deps]
GeoStats = "dcc97b0b-8ce5-5539-9008-bb190f959ef6"
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
